version: '3'
services:
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  # pgsql:
  #   image: postgres:alpine
  #   ports:
  #     - '5432:5432'
  #   container_name: 'pgsql'
  #   restart: always
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  # pg-data: # app:
  cache:
    driver: local